name: Pokedex CI

on: 
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [16.x, 17.x, 18.x]
    
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build


